<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Lavanya-Laptop" failures="6" tests="6" name="Test" time="13.604" errors="0" timestamp="2022-08-02T17:29:10 EDT">
  <testcase classname="com.hrmapp.testcases.SearchUser" name="empNa" time="0.015">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrmapp.resources.Listeners.onTestStart(Listeners.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- empNa -->
  <testcase classname="com.hrmapp.testcases.SearchUserTest" name="userFind" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrmapp.resources.Listeners.onTestStart(Listeners.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- userFind -->
  <testcase classname="com.hrmapp.testcases.ValidLoginTest" name="LoginTest" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrmapp.resources.Listeners.onTestStart(Listeners.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase classname="com.hrmapp.testcases.SearchUserTest" name="userX" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrmapp.resources.Listeners.onTestStart(Listeners.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- userX -->
  <testcase classname="com.hrmapp.testcases.SearchUser" name="userNamefield" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrmapp.resources.Listeners.onTestStart(Listeners.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- userNamefield -->
  <testcase classname="com.hrmapp.testcases.ValidLoginTest" name="verifyTitleTest" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrmapp.resources.Listeners.onTestStart(Listeners.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- verifyTitleTest -->
  <testcase classname="com.hrmapp.base.BaseClass" name="@BeforeSuite loadConfig1" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite loadConfig1 -->
  <testcase classname="com.hrmapp.base.BaseClass" name="@BeforeSuite loadConfig1" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite loadConfig1 -->
</testsuite> <!-- Test -->
